{% set name = "marsilea" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marsilea-{{ version }}.tar.gz
  sha256: 8c935bc3cc9cd4b3c87c2ad375cd2dfd5625e72bd787244ef1200d1a60412089

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base >=3.6
    - seaborn
    - scipy
    - legendkit
    - platformdirs

test:
  imports:
    - marsilea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Marsilea-viz/marsilea
  summary: Declarative creation of composable visualization for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
