{% set name = "marsilea" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marsilea-{{ version }}.tar.gz
  sha256: 2804920f8087cd8e5e9bb2b0bddf6393731808c2bba6b305bb8dc0344b0241f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base >=3.6
    - seaborn
    - scipy
    - legendkit
    - platformdirs

test:
  imports:
    - marsilea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Marsilea-viz/marsilea
  summary: Declarative creation of composable visualization for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
