{% set name = "marsilea" %}
{% set version = "0.7.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/marsilea-{{ version }}.tar.gz
  sha256: a0a073f1b502775b62d6f896294a47edccfbbd14a4151c04b3ead2c1c9843204

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    # pandas[parquet] extra, needed by marsilea.dataset for read_parquet
    - pyarrow
    - matplotlib-base >=3.6
    - seaborn
    - scipy
    - legendkit >=0.4.1
    - platformdirs

test:
  imports:
    - marsilea
    - oncoprinter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Marsilea-viz/marsilea
  summary: Declarative creation of composable visualization for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
