{% set name = "marsilea" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marsilea-{{ version }}.tar.gz
  sha256: 9deef921f562df8364f7c16afd77deb44b49d4f38aad4d528d5ad96e21b0b6cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base >=3.6
    - seaborn
    - scipy
    - legendkit
    - platformdirs

test:
  imports:
    - marsilea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Marsilea-viz/marsilea
  summary: Declarative creation of composable visualization for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
