{% set name = "marsilea" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marsilea-{{ version }}.tar.gz
  sha256: 11ea59bccaec6c0014e8fb17bcbaa34cd6f776e8db30ade213240dbca5105255

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - matplotlib-base >=3.6
    - seaborn
    - scipy
    - legendkit
    - platformdirs

test:
  imports:
    - marsilea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Marsilea-viz/marsilea
  summary: Declarative creation of composable visualization for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
